Restored old version of qpidd.init

diff --git a/debian/qpidd.init b/debian/qpidd.init
--- a/debian/qpidd.init
+++ b/debian/qpidd.init
@@ -1,168 +1,105 @@
-#!/bin/sh
-#
-# Licensed to the Apache Software Foundation (ASF) under one
-# or more contributor license agreements.  See the NOTICE file
-# distributed with this work for additional information
-# regarding copyright ownership.  The ASF licenses this file
-# to you under the Apache License, Version 2.0 (the
-# "License"); you may not use this file except in compliance
-# with the License.  You may obtain a copy of the License at
-#
-#   http://www.apache.org/licenses/LICENSE-2.0
-#
-# Unless required by applicable law or agreed to in writing,
-# software distributed under the License is distributed on an
-# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
-# KIND, either express or implied.  See the License for the
-# specific language governing permissions and limitations
-# under the License.
-#
-#
-# qpidd        Startup script for the Qpid messaging daemon.
-#
-
+#! /bin/sh
 ### BEGIN INIT INFO
-# Provides: qpidd
-# Required-Start: $local_fs $remote_fs $syslog
-# Required-Stop: $local_fs $remote_fs $syslog
-# Default-Start: 2 3 4 5
-# Default-Stop: 0 1 6
+# Provides:          qpidd
+# Required-Start:    $remote_fs $syslog
+# Required-Stop:     $remote_fs $syslog
+# Default-Start:     2 3 4 5
+# Default-Stop:      0 1 6
 # Short-Description: System V script for controlling qpidd
-# Description: Qpidd is an AMQP broker. It receives, stores, routes and	forwards messages using the AMQP protcol.
+# Description:       Controls the life cycle for the Qpid broker daemon.
 ### END INIT INFO
 
-# chkconfig: - 85 15
-# description: Qpidd is an AMQP broker. It receives, stores, routes and forwards messages using the AMQP protcol.
-# processname: qpidd
+# PATH should only include /usr/* if it runs after the mountnfs.sh script
+PATH=/sbin:/usr/sbin:/bin:/usr/bin
+DESC="Qpid Broker"
+NAME=qpidd
+CONFFILE=/etc/qpid/qpidd.conf
+DAEMON=/usr/sbin/$NAME
+DAEMON_ARGS="--config $CONFFILE"
+PIDFILE=/var/run/$NAME.pid
+SCRIPTNAME=/etc/init.d/$NAME
 
-prog=qpidd
-lockfile=/var/lock/subsys/$prog
-pidfile=/var/run/qpidd.pid
+# Exit if the package is not installed
+[ -x "$DAEMON" ] || exit 0
 
-# The following variables can be overridden in /etc/sysconfig/$prog
-QPID_INIT=/etc/rc.d/init.d/$prog
-QPID_BIN=/usr/sbin/$prog
-QPID_DATA_DIR=/var/lib/qpidd
-QPID_CONFIG=/etc/qpid/qpidd.conf
-QPID_HA=/usr/bin/qpid-ha
-QPID_HA_OPTIONS="--config $QPID_CONFIG"
+# Read configuration variable file if it is present
+[ -r /etc/default/$NAME ] && . /etc/default/$NAME
 
-# Source configuration
-test -f /etc/sysconfig/$prog && source /etc/sysconfig/$prog
-source /etc/rc.d/init.d/functions
+# Load the VERBOSE setting and other rcS variables
+. /lib/init/vars.sh
 
-# Data dir: respect the config file if set.
-grep -q '^ *data-dir *=' $QPID_CONFIG || QPIDD_OPTIONS="$QPIDD_OPTIONS --data-dir=$QPID_DATA_DIR"
+. /lib/lsb/init-functions
 
-# Check for HA configuration
-if grep -iq '^ *ha-cluster *= *\(true\|on\|1\|yes\)' $QPID_CONFIG; then
-    # HA is configured, do some extra checks.
-    test -x  $QPID_HA || { echo "HA configured but $QPID_HA not found"; return 5; }
-
-    ha_ping() {	$QPID_HA $QPID_HA_OPTIONS ping >/dev/null 2>&1; }
-
-    ha_allow_stop() {
-        # Primary script does not stop backup brokers and vice versa.
-	if $QPID_HA $QPID_HA_OPTIONS status --is-primary 2>&1 > /dev/null; then
-	    [ "$1" = primary ] || { echo -n "stop primary broker with 'qpidd-primary stop'"; return 1; }
-	else
-	    [ "$1" = primary ] && { echo -n "stop backup broker with 'qpidd stop'"; return 1; }
-	fi
-	return 0
-    }
-else
-    # No HA configuration, HA checks are no-ops.
-    ha_ping() { true; }
-    ha_allow_stop() { true; }
-fi
-
-# Check presence of executables/scripts
-for f in $QPID_BIN; do
-    test -x $f || { echo "$f not found or not executable"; exit 5; }
-done
-
-RETVAL=0
-
-# Ensure user has sufficient permissions
-runuser -s /bin/sh qpidd -c "echo x > /dev/null" 2> /dev/null || RETVAL=4
-if [ $RETVAL = 4 ]; then
-    echo "user had insufficient privilege";
-    exit $RETVAL
-fi
-
-do_status() {
-    # Check PID file and ping for liveness
-    MESSAGE=$(status -p $pidfile $prog) && {
-	ha_ping || return 1
-    }
-    RC=$?
-    echo $MESSAGE
-    return $RC
+do_start()
+{
+        start-stop-daemon --start --quiet --pidfile $PIDFILE --exec $DAEMON --test > /dev/null \
+                || return 1
+        start-stop-daemon --start --quiet --pidfile $PIDFILE --exec $DAEMON --make-pidfile --background -- \
+                $DAEMON_ARGS \
+                || return 2
 }
 
-FLOCK_FD=9
-# Ensure no concurrent start/stop of services.
-lock() {
-    [ "$QPID_HA_LOCK_HELD" ] || { # Held by caller
-	exec 9< $QPID_INIT
-	flock $FLOCK_FD
-    }
+do_stop()
+{
+        start-stop-daemon --stop --quiet --retry=30 --pidfile $PIDFILE --name $NAME
+        RETVAL="$?"
+        [ "$RETVAL" = 2 ] && return 2
+        start-stop-daemon --stop --quiet --oknodo --retry=30 --exec $DAEMON
+        [ "$?" = 2 ] && return 2
+        rm -f $PIDFILE
+        return "$RETVAL"
 }
 
-start() {
-    lock
-    echo -n $"Starting Qpid AMQP daemon: "
-    touch $pidfile
-    chown qpidd.qpidd $pidfile
-    [ -x /sbin/restorecon ] && /sbin/restorecon $pidfile
-    daemon --pidfile $pidfile --check $prog --user qpidd $QPID_BIN --config $QPID_CONFIG --daemon $QPIDD_OPTIONS --close-fd $FLOCK_FD --pidfile $pidfile
-    RETVAL=$?
-    echo
-    [ $RETVAL = 0 ] && touch $lockfile
-    return $RETVAL
+do_reload() {
+        start-stop-daemon --stop --signal 1 --quiet --pidfile $PIDFILE --name $NAME
+        return 0
 }
 
-stop() {
-    lock
-    if ha_allow_stop $1; then
-	echo -n $"Stopping Qpid AMQP daemon: "
-	killproc -p ${pidfile} $prog
-	RETVAL=$?
-	[ $RETVAL = 0 ] && rm -f ${lockfile} ${pidfile}
-    fi
-    [ "$RETVAL" = 0 ] && success
-    echo
-    return $RETVAL
-}
-
-
-reload() {
-    echo 1>&2 $"$0: reload not supported"
-    return 3
-}
-
-restart() {
-    stop && start
-}
-
-# See how we were called.
 case "$1" in
-    start|stop|restart|reload)
-	$1 $2
-	;;
-    status)
-	do_status
-	RETVAL=$?
-	;;
-    force-reload)
-	restart
-	;;
-    try-restart|condrestart)
-	[ -e $lockfile ] && restart || :
-	;;
-    *)
-	echo 1>&2 $"Usage: $0 {start|stop|status|restart|condrestart|try-restart|force-reload}"
-	exit 2
+  start)
+        [ "$VERBOSE" != no ] && log_daemon_msg "Starting $DESC" "$NAME"
+        do_start
+        case "$?" in
+                0|1) [ "$VERBOSE" != no ] && log_end_msg 0 ;;
+                2) [ "$VERBOSE" != no ] && log_end_msg 1 ;;
+        esac
+        ;;
+  stop)
+        [ "$VERBOSE" != no ] && log_daemon_msg "Stopping $DESC" "$NAME"
+        do_stop
+        case "$?" in
+                0|1) [ "$VERBOSE" != no ] && log_end_msg 0 ;;
+                2) [ "$VERBOSE" != no ] && log_end_msg 1 ;;
+        esac
+        log_end_msg 0
+        ;;
+  status)
+        status_of_proc "$DAEMON" "$NAME" && exit 0 || exit $?
+        ;;
+  restart|force-reload)
+        log_daemon_msg "Restarting $DESC" "$NAME"
+        do_stop
+        case "$?" in
+          0|1)
+                do_start
+                case "$?" in
+                        0) log_end_msg 0 ;;
+                        1) log_end_msg 1 ;; # Old process is still running
+                        *) log_end_msg 1 ;; # Failed to start
+                esac
+                ;;
+          *)
+                # Failed to stop
+                log_end_msg 1
+                ;;
+        esac
+        ;;
+  *)
+        echo "Usage: $SCRIPTNAME {start|stop|status|restart|force-reload}" >&2
+        exit 3
+        ;;
 esac
 
-exit $RETVAL
+exit 0
+
+# DEBHELPER #
